'use strict';
// ============================================================
// SHATTERED REALMS — Archmage Cards + All Tokens
// ============================================================

// ARCHMAGE STARTER DECK
CARD_DEFS['M001'] = { id:'M001', hero:'archmage', name:'Arcane Familiar', type:'minion', cost:2, starter:true, isToken:false, baseAtk:1, baseHp:3, kw:{}, text:'Surge: Gain +1/+0 until end of turn.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>window.Engine.buffMinion(G,uid,1,0,false), onPlay:null };
CARD_DEFS['M002'] = { id:'M002', hero:'archmage', name:'Cloudwisp', type:'minion', cost:1, starter:true, isToken:false, baseAtk:1, baseHp:2, kw:{}, text:'Battlecry: Scout 1.', battlecry:(G,uid,idx)=>window.Engine.scry(G,idx,1), lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M003'] = { id:'M003', hero:'archmage', name:'Rune Scholar', type:'minion', cost:3, starter:true, isToken:false, baseAtk:1, baseHp:4, kw:{ward:1}, text:'Ward 1. Inspire: Gain 1 Insight.', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>window.Engine.gainInsight(G,idx,1), rally:null, surge:null, onPlay:null };
CARD_DEFS['M004'] = { id:'M004', hero:'archmage', name:'Spellweaver Initiate', type:'minion', cost:2, starter:true, isToken:false, baseAtk:2, baseHp:2, kw:{}, text:'Surge: Draw a card (once per turn).', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>{ if(window.Engine.getPlayer(G,idx).instantsPlayedThisTurn===1) window.Engine.drawCards(G,idx,1); }, onPlay:null };
CARD_DEFS['M005'] = { id:'M005', hero:'archmage', name:'Frost Sentinel', type:'minion', cost:3, starter:true, isToken:false, baseAtk:0, baseHp:5, kw:{defender:true}, text:'Defender. Battlecry: Freeze target enemy minion.', battlecry:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.freezeMinion(G,targets[0],1); }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M006'] = { id:'M006', hero:'archmage', name:'Counterspell', type:'instant', cost:2, starter:true, isToken:false, kw:{}, isCounter:true, text:'Counter target spell.', onPlay:(G,uid,idx)=>window.Engine.log(G,'Counterspell resolves!'), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M007'] = { id:'M007', hero:'archmage', name:'Arcane Recoil', type:'instant', cost:2, starter:true, isToken:false, kw:{}, text:'Return target minion to its owner\'s hand.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.returnToHand(G,targets[0]); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M008'] = { id:'M008', hero:'archmage', name:'Frostbolt', type:'instant', cost:1, starter:true, isToken:false, kw:{}, text:'Deal 2 damage to target minion and Freeze it.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.dealDamage(G,targets[0],2,null);window.Engine.freezeMinion(G,targets[0],1);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M009'] = { id:'M009', hero:'archmage', name:'Arcane Intellect', type:'sorcery', cost:3, starter:true, isToken:false, kw:{}, text:'Draw 2 cards.', onPlay:(G,uid,idx)=>window.Engine.drawCards(G,idx,2), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M010'] = { id:'M010', hero:'archmage', name:'Mana Surge', type:'instant', cost:1, starter:true, isToken:false, kw:{}, text:'Gain 2 mana this turn.', onPlay:(G,uid,idx)=>window.Engine.gainMana(G,idx,2), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };

// ARCHMAGE SHOP MINIONS
CARD_DEFS['M011'] = { id:'M011', hero:'archmage', name:'Apprentice Scribe', type:'minion', cost:1, starter:false, isToken:false, baseAtk:1, baseHp:2, kw:{}, text:'Surge: Scout 1.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>window.Engine.scry(G,idx,1), onPlay:null };
CARD_DEFS['M012'] = { id:'M012', hero:'archmage', name:'Mana Sprite', type:'minion', cost:1, starter:false, isToken:false, baseAtk:0, baseHp:2, kw:{}, text:'Inspire: Gain 1 Insight.', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>window.Engine.gainInsight(G,idx,1), rally:null, surge:null, onPlay:null };
CARD_DEFS['M013'] = { id:'M013', hero:'archmage', name:'Mirror Image', type:'minion', cost:1, starter:false, isToken:false, baseAtk:0, baseHp:3, kw:{defender:true,flash:true}, text:'Defender. Flash.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M014'] = { id:'M014', hero:'archmage', name:'Chrono Wisp', type:'minion', cost:2, starter:false, isToken:false, baseAtk:2, baseHp:2, kw:{}, text:'Battlecry: Freeze target enemy minion.', battlecry:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.freezeMinion(G,targets[0],1); }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M015'] = { id:'M015', hero:'archmage', name:'Arcane Archivist', type:'minion', cost:2, starter:false, isToken:false, baseAtk:1, baseHp:3, kw:{}, text:'Battlecry: Draw a card. Gain 1 Insight.', battlecry:(G,uid,idx)=>{ window.Engine.drawCards(G,idx,1); window.Engine.gainInsight(G,idx,1); }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M016'] = { id:'M016', hero:'archmage', name:'Void Moth', type:'minion', cost:2, starter:false, isToken:false, baseAtk:2, baseHp:2, kw:{stealth:true}, text:'Stealth.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M017'] = { id:'M017', hero:'archmage', name:'Mist Phantom', type:'minion', cost:2, starter:false, isToken:false, baseAtk:2, baseHp:3, kw:{hexproof:true}, text:'Hexproof.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M018'] = { id:'M018', hero:'archmage', name:'Phase Walker', type:'minion', cost:2, starter:false, isToken:false, baseAtk:2, baseHp:2, kw:{flash:true}, text:'Flash. Battlecry: If played during opponent\'s turn, gain +1/+1.', battlecry:(G,uid,idx)=>{ if(G.activePlayer!==idx) window.Engine.buffMinion(G,uid,1,1,true); }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M019'] = { id:'M019', hero:'archmage', name:'Echo Mage', type:'minion', cost:3, starter:false, isToken:false, baseAtk:1, baseHp:4, kw:{}, text:'Surge: Copy next instant into hand at cost 0 (once per turn).', specialAbility:'surgeEchoInstant', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M020'] = { id:'M020', hero:'archmage', name:'Frost Witch', type:'minion', cost:3, starter:false, isToken:false, baseAtk:2, baseHp:3, kw:{}, text:'Battlecry: Freeze target enemy. Inspire: Freeze a random enemy minion.', battlecry:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.freezeMinion(G,targets[0],1); }, lastBreath:null, inspire:(G,uid,idx)=>{ const e=window.Engine.getEnemyMinions(G,idx); if(e.length>0) window.Engine.freezeMinion(G,window.Engine.rand(e).uid,1); }, rally:null, surge:null, onPlay:null };
CARD_DEFS['M021'] = { id:'M021', hero:'archmage', name:'Thought Siphon', type:'minion', cost:3, starter:false, isToken:false, baseAtk:2, baseHp:3, kw:{}, text:'Whenever you counter a spell, gain 3 Insight and draw a card.', specialAbility:'onCounter_gainInsightDraw', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M022'] = { id:'M022', hero:'archmage', name:'Windborne Seer', type:'minion', cost:3, starter:false, isToken:false, baseAtk:2, baseHp:3, kw:{ward:2}, text:'Ward 2. Surge: Gain +0/+1.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>window.Engine.buffMinion(G,uid,0,1,true), onPlay:null };
CARD_DEFS['M023'] = { id:'M023', hero:'archmage', name:'Arcane Sentinel', type:'minion', cost:3, starter:false, isToken:false, baseAtk:1, baseHp:5, kw:{defender:true,ward:2}, text:'Defender. Ward 2. Surge: Deal 1 damage to a random enemy minion.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>{ const e=window.Engine.getEnemyMinions(G,idx); if(e.length>0) window.Engine.dealDamage(G,window.Engine.rand(e).uid,1,null); }, onPlay:null };
CARD_DEFS['M024'] = { id:'M024', hero:'archmage', name:'Ethereal Scholar', type:'minion', cost:4, starter:false, isToken:false, baseAtk:3, baseHp:4, kw:{ward:1}, text:'Ward 1. Inspire: Gain 2 Insight. Surge: Draw a card (once per turn).', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>window.Engine.gainInsight(G,idx,2), rally:null, surge:(G,uid,idx)=>{ if(window.Engine.getPlayer(G,idx).instantsPlayedThisTurn===1) window.Engine.drawCards(G,idx,1); }, onPlay:null };
CARD_DEFS['M025'] = { id:'M025', hero:'archmage', name:'Spell Thief', type:'minion', cost:4, starter:false, isToken:false, baseAtk:2, baseHp:3, kw:{flash:true}, text:'Flash. Battlecry: Counter target spell.', battlecry:(G,uid,idx)=>window.Engine.log(G,'Spell Thief counters a spell!'), lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M026'] = { id:'M026', hero:'archmage', name:'Temporal Adept', type:'minion', cost:4, starter:false, isToken:false, baseAtk:3, baseHp:3, kw:{}, text:'Battlecry: Return target enemy minion to hand. Gain Insight equal to its cost.', battlecry:(G,uid,idx,targets)=>{ if(targets&&targets[0]){const m=window.Engine.getMinion(G,targets[0]);if(m){const c=m.cost||0;window.Engine.returnToHand(G,targets[0]);window.Engine.gainInsight(G,idx,c);}} }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M027'] = { id:'M027', hero:'archmage', name:'Void Warden', type:'minion', cost:4, starter:false, isToken:false, baseAtk:1, baseHp:6, kw:{defender:true,hexproof:true}, text:'Defender. Hexproof. Whenever an enemy attacks, freeze it after combat.', specialAbility:'onEnemyAttack_freeze', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M028'] = { id:'M028', hero:'archmage', name:'Arcane Reflector', type:'minion', cost:5, starter:false, isToken:false, baseAtk:2, baseHp:5, kw:{ward:3}, text:'Ward 3. Surge: Deal 2 damage to a random enemy minion.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>{ const e=window.Engine.getEnemyMinions(G,idx); if(e.length>0) window.Engine.dealDamage(G,window.Engine.rand(e).uid,2,null); }, onPlay:null };
CARD_DEFS['M029'] = { id:'M029', hero:'archmage', name:'Chronomancer', type:'minion', cost:5, starter:false, isToken:false, baseAtk:3, baseHp:5, kw:{ward:1}, text:'Ward 1. Battlecry: Take an extra draft pick this turn.', battlecry:(G,uid,idx)=>window.Engine.extraDraft(G,idx,1), lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M030'] = { id:'M030', hero:'archmage', name:'Stormcaller', type:'minion', cost:5, starter:false, isToken:false, baseAtk:4, baseHp:5, kw:{ward:1}, text:'Ward 1. Surge: Deal 1 damage to all enemy minions.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>{ window.Engine.getEnemyMinions(G,idx).forEach(m=>window.Engine.dealDamage(G,m.uid,1,null)); }, onPlay:null };
CARD_DEFS['M031'] = { id:'M031', hero:'archmage', name:'Mindbreaker', type:'minion', cost:6, starter:false, isToken:false, baseAtk:3, baseHp:5, kw:{ward:2}, text:'Ward 2. Battlecry: Opponent discards a random card. Gain Insight equal to its cost.', battlecry:(G,uid,idx)=>{ const opp=window.Engine.getPlayer(G,1-idx); if(opp.hand.length>0){const r=window.Engine.rand(opp.hand);opp.hand=opp.hand.filter(c=>c.uid!==r.uid);window.Engine.gainInsight(G,idx,r.cost||0);window.Engine.log(G,'Mindbreaker discards '+r.name+'!');} }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M032'] = { id:'M032', hero:'archmage', name:'Leyline Guardian', type:'minion', cost:6, starter:false, isToken:false, baseAtk:2, baseHp:7, kw:{defender:true,hexproof:true}, text:'Defender. Hexproof. Inspire: Gain 3 Insight. All friendly minions gain Ward 1 until end of turn.', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>{ window.Engine.gainInsight(G,idx,3); window.Engine.getFriendlyMinions(G,idx).forEach(m=>window.Engine.giveKeywordTemp(G,m.uid,'ward',1)); }, rally:null, surge:null, onPlay:null };
CARD_DEFS['M033'] = { id:'M033', hero:'archmage', name:'Arcane Sovereign', type:'minion', cost:7, starter:false, isToken:false, baseAtk:4, baseHp:7, kw:{hexproof:true,ward:1}, text:'Hexproof. Ward 1. Surge: Gain 2 Insight and draw a card.', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:(G,uid,idx)=>{ window.Engine.gainInsight(G,idx,2); window.Engine.drawCards(G,idx,1); }, onPlay:null };
CARD_DEFS['M034'] = { id:'M034', hero:'archmage', name:'Temporal Dragon', type:'minion', cost:8, starter:false, isToken:false, baseAtk:5, baseHp:8, kw:{ward:2}, text:'Ward 2. Battlecry: Freeze all enemy minions.', battlecry:(G,uid,idx)=>{ window.Engine.getEnemyMinions(G,idx).forEach(m=>window.Engine.freezeMinion(G,m.uid,1)); }, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
CARD_DEFS['M035'] = { id:'M035', hero:'archmage', name:'Infinite Wyrm', type:'minion', cost:8, starter:false, isToken:false, baseAtk:5, baseHp:8, kw:{ward:4}, text:'Ward 4. Inspire: Gain 3 Insight. Surge: +1/+0 and deal 2 damage to random enemy.', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>window.Engine.gainInsight(G,idx,3), rally:null, surge:(G,uid,idx)=>{ window.Engine.buffMinion(G,uid,1,0,true); const e=window.Engine.getEnemyMinions(G,idx); if(e.length>0) window.Engine.dealDamage(G,window.Engine.rand(e).uid,2,null); }, onPlay:null };
CARD_DEFS['M036'] = { id:'M036', hero:'archmage', name:'Dreamweaver Sphinx', type:'minion', cost:9, starter:false, isToken:false, baseAtk:5, baseHp:8, kw:{hexproof:true,ward:1}, text:'Hexproof. Ward 1. Inspire: Draw a card, gain 2 Insight. When you play an instant, freeze a random enemy.', specialAbility:'onInstantPlayed_freeze', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>{ window.Engine.drawCards(G,idx,1); window.Engine.gainInsight(G,idx,2); }, rally:null, surge:null, onPlay:null };
CARD_DEFS['M037'] = { id:'M037', hero:'archmage', name:'Nexus of All Spells', type:'minion', cost:10, starter:false, isToken:false, baseAtk:4, baseHp:11, kw:{hexproof:true,ward:5}, text:'Hexproof. Ward 5. Inspire: Gain 4 Insight. Surge: Copy the spell.', specialAbility:'surgeSpellCopy', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>window.Engine.gainInsight(G,idx,4), rally:null, surge:null, onPlay:null };
CARD_DEFS['M038'] = { id:'M038', hero:'archmage', name:'Omniscience Avatar', type:'minion', cost:12, starter:false, isToken:false, baseAtk:7, baseHp:12, kw:{hexproof:true,indestructible:true}, text:'Hexproof. Indestructible. Enters tapped 2 turns. Inspire: Gain 5 Insight, draw 2, freeze all enemies.', specialAbility:'doubleEntryTap', battlecry:null, lastBreath:null, inspire:(G,uid,idx)=>{ window.Engine.gainInsight(G,idx,5); window.Engine.drawCards(G,idx,2); window.Engine.getEnemyMinions(G,idx).forEach(m=>window.Engine.freezeMinion(G,m.uid,1)); }, rally:null, surge:null, onPlay:null };

// ARCHMAGE SHOP INSTANTS
CARD_DEFS['M039'] = { id:'M039', hero:'archmage', name:'Arcane Dart', type:'instant', cost:1, starter:false, isToken:false, kw:{}, text:'Deal 1 damage to target minion. Draw a card.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.dealDamage(G,targets[0],1,null); window.Engine.drawCards(G,idx,1); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M040'] = { id:'M040', hero:'archmage', name:'Dispel', type:'instant', cost:1, starter:false, isToken:false, kw:{}, text:'Silence target minion.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.silenceMinion(G,targets[0]); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M041'] = { id:'M041', hero:'archmage', name:'Flash Freeze', type:'instant', cost:1, starter:false, isToken:false, kw:{}, text:'Freeze target minion. If already frozen, deal 3 damage instead.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){const m=window.Engine.getMinion(G,targets[0]);if(m&&m.frozenTurns>0){window.Engine.dealDamage(G,targets[0],3,null);}else{window.Engine.freezeMinion(G,targets[0],1);}} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M042'] = { id:'M042', hero:'archmage', name:'Spell Shield', type:'instant', cost:1, starter:false, isToken:false, kw:{}, text:'Give a friendly minion Ward 3 until end of turn.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.giveKeywordTemp(G,targets[0],'ward',3); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M043'] = { id:'M043', hero:'archmage', name:'Negate', type:'instant', cost:2, starter:false, isToken:false, kw:{}, isCounter:true, counterSubtype:'instant', text:'Counter target instant.', onPlay:(G,uid,idx)=>window.Engine.log(G,'Negate: target instant countered!'), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M044'] = { id:'M044', hero:'archmage', name:'Mana Leak', type:'instant', cost:2, starter:false, isToken:false, kw:{}, isCounter:true, text:'Counter target spell unless controller pays 3 extra mana.', onPlay:(G,uid,idx)=>window.Engine.log(G,'Mana Leak: spell countered!'), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M045'] = { id:'M045', hero:'archmage', name:'Temporal Shift', type:'instant', cost:2, starter:false, isToken:false, kw:{}, text:'Return target minion to its owner\'s hand. Its controller draws a card.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){const m=window.Engine.getMinion(G,targets[0]);if(m){const owner=m.owner;window.Engine.returnToHand(G,targets[0]);window.Engine.drawCards(G,owner,1);}} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M046'] = { id:'M046', hero:'archmage', name:'Arcane Burst', type:'instant', cost:2, starter:false, isToken:false, kw:{}, text:'Deal 3 damage to target minion.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.dealDamage(G,targets[0],3,null); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M047'] = { id:'M047', hero:'archmage', name:'Frost Nova', type:'instant', cost:3, starter:false, isToken:false, kw:{}, text:'Freeze all enemy minions for 1 turn.', onPlay:(G,uid,idx)=>{ window.Engine.getEnemyMinions(G,idx).forEach(m=>window.Engine.freezeMinion(G,m.uid,1)); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M048'] = { id:'M048', hero:'archmage', name:'Essence Scatter', type:'instant', cost:2, starter:false, isToken:false, kw:{}, isCounter:true, counterSubtype:'minion', text:'Counter target minion spell.', onPlay:(G,uid,idx)=>window.Engine.log(G,'Essence Scatter: minion countered!'), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M049'] = { id:'M049', hero:'archmage', name:'Redirect', type:'instant', cost:2, starter:false, isToken:false, kw:{}, text:'Change the target of a spell or ability.', onPlay:(G,uid,idx)=>window.Engine.log(G,'Redirect: spell retargeted!'), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M050'] = { id:'M050', hero:'archmage', name:'Thought Erasure', type:'instant', cost:3, starter:false, isToken:false, kw:{}, text:'Opponent discards a non-minion card. Gain 2 Insight.', onPlay:(G,uid,idx)=>{ const opp=window.Engine.getPlayer(G,1-idx);const spells=opp.hand.filter(c=>c.type!=='minion');if(spells.length>0){const r=window.Engine.rand(spells);opp.hand=opp.hand.filter(c=>c.uid!==r.uid);window.Engine.log(G,'Thought Erasure discards '+r.name+'!');}window.Engine.gainInsight(G,idx,2); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M051'] = { id:'M051', hero:'archmage', name:'Arcane Denial', type:'instant', cost:3, starter:false, isToken:false, kw:{}, isCounter:true, text:'Counter target spell. Gain 3 Insight.', onPlay:(G,uid,idx)=>{ window.Engine.log(G,'Arcane Denial: spell countered!'); window.Engine.gainInsight(G,idx,3); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M052'] = { id:'M052', hero:'archmage', name:'Chrono Stasis', type:'instant', cost:3, starter:false, isToken:false, kw:{}, text:'Freeze target minion for 2 upkeeps.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.freezeMinion(G,targets[0],2); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M053'] = { id:'M053', hero:'archmage', name:'Polymorph', type:'instant', cost:4, starter:false, isToken:false, kw:{}, text:'Transform target minion into a 1/1 Sheep with no abilities.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]) window.Engine.transformMinion(G,targets[0],'TK_SHEEP'); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M054'] = { id:'M054', hero:'archmage', name:'Mystical Tutor', type:'instant', cost:4, starter:false, isToken:false, kw:{}, text:'Scout 5. Draw a card.', onPlay:(G,uid,idx)=>{ window.Engine.scry(G,idx,5); window.Engine.drawCards(G,idx,1); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M055'] = { id:'M055', hero:'archmage', name:'Force of Will', type:'instant', cost:4, starter:false, isToken:false, kw:{}, isCounter:true, text:'Counter target spell.', onPlay:(G,uid,idx)=>window.Engine.log(G,'Force of Will: spell countered!'), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M056'] = { id:'M056', hero:'archmage', name:'Absorb', type:'instant', cost:4, starter:false, isToken:false, kw:{}, isCounter:true, text:'Counter target spell. Gain 3 Insight.', onPlay:(G,uid,idx)=>{ window.Engine.log(G,'Absorb: spell countered!'); window.Engine.gainInsight(G,idx,3); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M057'] = { id:'M057', hero:'archmage', name:'Cyclone', type:'instant', cost:5, starter:false, isToken:false, kw:{}, text:'Return all enemy minions with ATK 3 or less to hand.', onPlay:(G,uid,idx)=>{ const tgts=window.Engine.getEnemyMinions(G,idx).filter(m=>window.Engine.getEffectiveAtk(m)<=3); for(const m of tgts) window.Engine.returnToHand(G,m.uid); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M058'] = { id:'M058', hero:'archmage', name:'Mindshatter', type:'instant', cost:5, starter:false, isToken:false, kw:{}, isCounter:true, text:'Counter target spell. Opponent discards a random card. Gain Insight equal to its cost.', onPlay:(G,uid,idx)=>{ window.Engine.log(G,'Mindshatter: spell countered!'); const opp=window.Engine.getPlayer(G,1-idx); if(opp.hand.length>0){const r=window.Engine.rand(opp.hand);opp.hand=opp.hand.filter(c=>c.uid!==r.uid);window.Engine.gainInsight(G,idx,r.cost||0);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M059'] = { id:'M059', hero:'archmage', name:'Time Stop', type:'instant', cost:6, starter:false, isToken:false, kw:{}, text:'End the current phase.', onPlay:(G,uid,idx)=>{ if(G.phase==='combat'){window.Engine.endCombat(G);}else{window.Engine.log(G,'Time Stop ends the action phase!');} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M060'] = { id:'M060', hero:'archmage', name:'Mass Polymorph', type:'instant', cost:7, starter:false, isToken:false, kw:{}, text:'Transform all enemy minions into 1/1 Sheep.', onPlay:(G,uid,idx)=>{ const enemies=window.Engine.getEnemyMinions(G,idx).slice(); for(const m of enemies) window.Engine.transformMinion(G,m.uid,'TK_SHEEP'); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M061'] = { id:'M061', hero:'archmage', name:'Overwhelming Intellect', type:'instant', cost:7, starter:false, isToken:false, kw:{}, isCounter:true, text:'Counter target spell. Draw 3 cards. Gain 4 Insight.', onPlay:(G,uid,idx)=>{ window.Engine.log(G,'Overwhelming Intellect: spell countered!'); window.Engine.drawCards(G,idx,3); window.Engine.gainInsight(G,idx,4); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M062'] = { id:'M062', hero:'archmage', name:'Absolute Zero', type:'instant', cost:8, starter:false, isToken:false, kw:{}, text:'Freeze all enemy minions for 2 upkeeps. Deal 2 damage to each.', onPlay:(G,uid,idx)=>{ const enemies=window.Engine.getEnemyMinions(G,idx).slice(); for(const m of enemies){window.Engine.freezeMinion(G,m.uid,2);window.Engine.dealDamage(G,m.uid,2,null);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };

// ARCHMAGE SHOP SORCERIES
CARD_DEFS['M063'] = { id:'M063', hero:'archmage', name:'Prestidigitation', type:'sorcery', cost:1, starter:false, isToken:false, kw:{}, text:'Draw a card. Gain 1 Insight.', onPlay:(G,uid,idx)=>{ window.Engine.drawCards(G,idx,1); window.Engine.gainInsight(G,idx,1); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M064'] = { id:'M064', hero:'archmage', name:'Scrying Pool', type:'sorcery', cost:2, starter:false, isToken:false, kw:{}, text:'Scout 3. Draw a card.', onPlay:(G,uid,idx)=>{ window.Engine.scry(G,idx,3); window.Engine.drawCards(G,idx,1); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M065'] = { id:'M065', hero:'archmage', name:'Arcane Recovery', type:'sorcery', cost:2, starter:false, isToken:false, kw:{}, text:'Return an instant from discard to hand. Gain 1 Insight.', onPlay:(G,uid,idx)=>{ const p=window.Engine.getPlayer(G,idx);const insts=p.discard.filter(c=>c.type==='instant');if(insts.length>0){const r=window.Engine.rand(insts);p.discard=p.discard.filter(c=>c.uid!==r.uid);p.hand.push(r);window.Engine.log(G,'Arcane Recovery returns '+r.name+' to hand.');}window.Engine.gainInsight(G,idx,1); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M066'] = { id:'M066', hero:'archmage', name:'Frozen Tomb', type:'sorcery', cost:3, starter:false, isToken:false, kw:{}, text:'Freeze target enemy minion for 2 upkeeps. Deal 2 damage.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.freezeMinion(G,targets[0],2);window.Engine.dealDamage(G,targets[0],2,null);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M067'] = { id:'M067', hero:'archmage', name:'Deep Research', type:'sorcery', cost:3, starter:false, isToken:false, kw:{}, text:'Draw 3 cards. Gain 2 Insight.', onPlay:(G,uid,idx)=>{ window.Engine.drawCards(G,idx,3); window.Engine.gainInsight(G,idx,2); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M068'] = { id:'M068', hero:'archmage', name:'Restock the Library', type:'sorcery', cost:3, starter:false, isToken:false, kw:{}, text:'Scout 3.', onPlay:(G,uid,idx)=>window.Engine.scry(G,idx,3), battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M069'] = { id:'M069', hero:'archmage', name:'Mana Drain', type:'sorcery', cost:4, starter:false, isToken:false, kw:{}, text:'Silence all enemy minions until end of turn. Gain 1 Insight per enemy.', onPlay:(G,uid,idx)=>{ const enemies=window.Engine.getEnemyMinions(G,idx); for(const m of enemies){m.tempSilenced=true;window.Engine.addEndOfTurnCleanup(G,{type:'tempSilence',uid:m.uid});}window.Engine.gainInsight(G,idx,enemies.length); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M070'] = { id:'M070', hero:'archmage', name:'Stolen Knowledge', type:'sorcery', cost:4, starter:false, isToken:false, kw:{}, text:'Copy a spell from opponent\'s hand into yours at cost 0. Gain 2 Insight.', onPlay:(G,uid,idx)=>{ const opp=window.Engine.getPlayer(G,1-idx);const spells=opp.hand.filter(c=>c.type!=='minion');if(spells.length>0){const r=window.Engine.rand(spells);const copy=JSON.parse(JSON.stringify(r));copy.uid='cc'+Date.now();copy.cost=0;window.Engine.getPlayer(G,idx).hand.push(copy);window.Engine.log(G,'Stolen Knowledge copies '+r.name+'!');}window.Engine.gainInsight(G,idx,2); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M071'] = { id:'M071', hero:'archmage', name:'Glacial Storm', type:'sorcery', cost:4, starter:false, isToken:false, kw:{}, text:'Deal 2 damage to all enemy minions. Freeze survivors.', onPlay:(G,uid,idx)=>{ const enemies=window.Engine.getEnemyMinions(G,idx).slice(); for(const m of enemies){window.Engine.dealDamage(G,m.uid,2,null);if(window.Engine.getMinion(G,m.uid)) window.Engine.freezeMinion(G,m.uid,1);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M072'] = { id:'M072', hero:'archmage', name:'Leyline Tap', type:'sorcery', cost:4, starter:false, isToken:false, kw:{}, text:'Gain 5 Insight. Draw a card.', onPlay:(G,uid,idx)=>{ window.Engine.gainInsight(G,idx,5); window.Engine.drawCards(G,idx,1); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M073'] = { id:'M073', hero:'archmage', name:'Transmutation', type:'sorcery', cost:5, starter:false, isToken:false, kw:{}, text:'Transform target minion into a copy of another minion on the battlefield.', onPlay:(G,uid,idx,targets)=>{ if(!targets||!targets[0])return; const all=window.Engine.getAllMinions(G).filter(m=>m.uid!==targets[0]); if(all.length>0){const ref=window.Engine.rand(all);window.Engine.transformMinion(G,targets[0],ref.defId);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M074'] = { id:'M074', hero:'archmage', name:'Mind Control', type:'sorcery', cost:6, starter:false, isToken:false, kw:{}, text:'Gain control of target enemy minion with ATK 4 or less.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){const m=window.Engine.getMinion(G,targets[0]);if(m&&window.Engine.getEffectiveAtk(m)<=4){G.battlefield=G.battlefield.filter(c=>c.uid!==m.uid);m.owner=idx;m.tapped=false;G.battlefield.push(m);window.Engine.log(G,'Mind Control takes '+m.name+'!');}} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M075'] = { id:'M075', hero:'archmage', name:'Knowledge Overload', type:'sorcery', cost:6, starter:false, isToken:false, kw:{}, text:'Draw 4 cards. Gain 5 Insight. Max hand size +2.', onPlay:(G,uid,idx)=>{ window.Engine.drawCards(G,idx,4); window.Engine.gainInsight(G,idx,5); window.Engine.getPlayer(G,idx).handSizeBonus+=2; }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M076'] = { id:'M076', hero:'archmage', name:'Temporal Cascade', type:'sorcery', cost:7, starter:false, isToken:false, kw:{}, text:'Return all minions to their owners\' hands. Gain 1 Insight per minion.', onPlay:(G,uid,idx)=>{ const all=window.Engine.getAllMinions(G).slice(); const count=all.length; for(const m of all) window.Engine.returnToHand(G,m.uid); window.Engine.gainInsight(G,idx,count); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M077'] = { id:'M077', hero:'archmage', name:'Arcane Supremacy', type:'sorcery', cost:8, starter:false, isToken:false, kw:{}, text:'Counter all spells opponent plays this turn. Gain 10 Insight.', onPlay:(G,uid,idx)=>{ window.Engine.getPlayer(G,idx).arcaneSupremacyActive=true; window.Engine.gainInsight(G,idx,10); window.Engine.log(G,'Arcane Supremacy: opponent spells countered this turn!'); }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M078'] = { id:'M078', hero:'archmage', name:'Omniscience', type:'sorcery', cost:10, starter:false, isToken:false, kw:{}, text:'Draw 5 cards. Gain 15 Insight. All spells cost 0 this turn.', onPlay:(G,uid,idx)=>{ window.Engine.drawCards(G,idx,5); window.Engine.gainInsight(G,idx,15); window.Engine.getPlayer(G,idx).omniscienceActive=true; }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };

// ARCHMAGE SHOP ENCHANTMENTS
CARD_DEFS['M079'] = { id:'M079', hero:'archmage', name:'Mana Crystal', type:'enchantment', cost:2, starter:false, isToken:false, kw:{}, text:'Inspire: Gain 1 additional mana this turn.', inspire:(G,uid,idx)=>window.Engine.gainMana(G,idx,1), onPlay:null, battlecry:null, lastBreath:null, rally:null, surge:null };
CARD_DEFS['M080'] = { id:'M080', hero:'archmage', name:'Arcane Ward', type:'enchantment', cost:2, starter:false, isToken:false, kw:{}, text:'All friendly minions have Ward 1.', specialAbility:'aura_arcaneWard', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M081'] = { id:'M081', hero:'archmage', name:'Frozen Aura', type:'enchantment', cost:3, starter:false, isToken:false, kw:{}, text:'Whenever an enemy minion enters, freeze it.', specialAbility:'onEnemyEnter_freeze', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M082'] = { id:'M082', hero:'archmage', name:'Spell Echo', type:'enchantment', cost:3, starter:false, isToken:false, kw:{}, text:'First instant you play each turn costs 1 less.', specialAbility:'firstInstantDiscount', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M083'] = { id:'M083', hero:'archmage', name:'Library of Eternity', type:'enchantment', cost:3, starter:false, isToken:false, kw:{}, text:'Max hand size +2. At start of upkeep, if below max, draw an extra card.', onPlay:(G,uid,idx)=>{ window.Engine.getPlayer(G,idx).handSizeBonus=(window.Engine.getPlayer(G,idx).handSizeBonus||0)+2; }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M084'] = { id:'M084', hero:'archmage', name:'Insight Engine', type:'enchantment', cost:4, starter:false, isToken:false, kw:{}, text:'Whenever you play an instant, gain 1 Insight.', specialAbility:'onInstantPlayed_gainInsight', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M085'] = { id:'M085', hero:'archmage', name:'Counterspell Nexus', type:'enchantment', cost:4, starter:false, isToken:false, kw:{}, text:'Whenever you counter a spell, draw a card and gain 2 Insight.', specialAbility:'onCounter_drawAndInsight', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M086'] = { id:'M086', hero:'archmage', name:'Temporal Barrier', type:'enchantment', cost:5, starter:false, isToken:false, kw:{}, text:'Whenever opponent plays a minion, freeze it and deal 1 damage.', specialAbility:'onEnemyMinionPlayed_freezeDamage', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M087'] = { id:'M087', hero:'archmage', name:'Arcane Singularity', type:'enchantment', cost:5, starter:false, isToken:false, kw:{}, text:'Surge: Gain 2 Insight. Inspire: All friendly Ward minions gain +0/+1.', surge:(G,uid,idx)=>window.Engine.gainInsight(G,idx,2), inspire:(G,uid,idx)=>{ window.Engine.getFriendlyMinions(G,idx).filter(m=>window.Engine.getKw(m,'ward')).forEach(m=>window.Engine.buffMinion(G,m.uid,0,1,true)); }, onPlay:null, battlecry:null, lastBreath:null, rally:null };
CARD_DEFS['M088'] = { id:'M088', hero:'archmage', name:'Leyline Network', type:'enchantment', cost:6, starter:false, isToken:false, kw:{}, text:'Inspire: Gain 2 extra mana and 2 Insight this turn.', inspire:(G,uid,idx)=>{ window.Engine.gainMana(G,idx,2); window.Engine.gainInsight(G,idx,2); }, onPlay:null, battlecry:null, lastBreath:null, rally:null, surge:null };
CARD_DEFS['M089'] = { id:'M089', hero:'archmage', name:'Stasis Field', type:'enchantment', cost:7, starter:false, isToken:false, kw:{}, text:'At start of each Upkeep, freeze the enemy minion with highest ATK.', specialAbility:'upkeepFreezeHighestATK', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M090'] = { id:'M090', hero:'archmage', name:'Arcane Omnipotence', type:'enchantment', cost:8, starter:false, isToken:false, kw:{}, text:'All instants/sorceries cost 2 less. When you play a spell, gain 2 Insight.', specialAbility:'omnipotenceCostReduction', onPlay:null, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };

// ARCHMAGE SHOP UPGRADES
CARD_DEFS['M091'] = { id:'M091', hero:'archmage', name:'Arcane Infusion', type:'upgrade', cost:1, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +0/+2 and Ward 1 permanently.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],0,2,true);window.Engine.giveKeyword(G,targets[0],'ward',1);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M092'] = { id:'M092', hero:'archmage', name:'Icy Enchantment', type:'upgrade', cost:2, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +1/+1 and "When this blocks, freeze the attacker."', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],1,1,true);const m=window.Engine.getMinion(G,targets[0]);if(m){if(!m.extraAbilities)m.extraAbilities=[];m.extraAbilities.push('freezeOnBlock');}} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M093'] = { id:'M093', hero:'archmage', name:'Arcane Amplifier', type:'upgrade', cost:2, starter:false, isToken:false, kw:{}, text:'Give a friendly minion Ward 2. If it already has Ward, also +1/+2.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){const m=window.Engine.getMinion(G,targets[0]);if(m&&m.wardCharges>0){window.Engine.buffMinion(G,targets[0],1,2,true);}window.Engine.giveKeyword(G,targets[0],'ward',2);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M094'] = { id:'M094', hero:'archmage', name:'Insight Siphon', type:'upgrade', cost:3, starter:false, isToken:false, kw:{}, text:'Whenever this minion deals combat damage, gain that much Insight.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){const m=window.Engine.getMinion(G,targets[0]);if(m){if(!m.extraAbilities)m.extraAbilities=[];m.extraAbilities.push('insightSiphon');}} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M095'] = { id:'M095', hero:'archmage', name:'Hexproof Mantle', type:'upgrade', cost:3, starter:false, isToken:false, kw:{}, text:'Give a friendly minion Hexproof and +0/+3 permanently.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.giveKeyword(G,targets[0],'hexproof',true);window.Engine.buffMinion(G,targets[0],0,3,true);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M096'] = { id:'M096', hero:'archmage', name:'Chrono Core', type:'upgrade', cost:4, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +1/+3 and Ward 2 permanently.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],1,3,true);window.Engine.giveKeyword(G,targets[0],'ward',2);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M097'] = { id:'M097', hero:'archmage', name:'Frost Rune', type:'upgrade', cost:4, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +1/+1 and "When this deals combat damage, freeze the target."', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],1,1,true);const m=window.Engine.getMinion(G,targets[0]);if(m){if(!m.extraAbilities)m.extraAbilities=[];m.extraAbilities.push('frostOnHit');}} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M098'] = { id:'M098', hero:'archmage', name:'Arcane Colossus Frame', type:'upgrade', cost:5, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +3/+3, Ward 3, and Hexproof permanently.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],3,3,true);window.Engine.giveKeyword(G,targets[0],'ward',3);window.Engine.giveKeyword(G,targets[0],'hexproof',true);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M099'] = { id:'M099', hero:'archmage', name:'Temporal Shell', type:'upgrade', cost:6, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +2/+5, Indestructible, and Ward 3 permanently.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],2,5,true);window.Engine.giveKeyword(G,targets[0],'indestructible',true);window.Engine.giveKeyword(G,targets[0],'ward',3);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };
CARD_DEFS['M100'] = { id:'M100', hero:'archmage', name:'Omniscience Core', type:'upgrade', cost:8, starter:false, isToken:false, kw:{}, text:'Give a friendly minion +4/+4, Ward 3, Hexproof, and Indestructible permanently.', onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.buffMinion(G,targets[0],4,4,true);window.Engine.giveKeyword(G,targets[0],'ward',3);window.Engine.giveKeyword(G,targets[0],'hexproof',true);window.Engine.giveKeyword(G,targets[0],'indestructible',true);} }, battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null };

// ============================================================
// ARCHMAGE CURSES
// ============================================================
CARD_DEFS['M101'] = { id:'M101', hero:'archmage', name:'Mana Drain', type:'curse', cost:1, starter:false, isToken:false, kw:{}, text:'Target enemy minion loses a random keyword. Gain 1 Insight.', targetType:'enemy_minion', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.removeRandomKeyword(G,targets[0]);window.Engine.gainInsight(G,idx,1);} } };
CARD_DEFS['M102'] = { id:'M102', hero:'archmage', name:'Arcane Disruption', type:'curse', cost:2, starter:false, isToken:false, kw:{}, text:'Target enemy minion loses a random keyword. Freeze it.', targetType:'enemy_minion', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.removeRandomKeyword(G,targets[0]);window.Engine.freezeMinion(G,targets[0],1);} } };
CARD_DEFS['M103'] = { id:'M103', hero:'archmage', name:'Spell Erosion', type:'curse', cost:3, starter:false, isToken:false, kw:{}, text:'Choose a keyword. Target enemy minion loses that keyword. Gain 2 Insight.', targetType:'enemy_minion', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){if(targets[1]){window.Engine.removeKeyword(G,targets[0],targets[1]);const m=window.Engine.getMinion(G,targets[0]);if(m)window.Engine.log(G,m.name+' loses '+targets[1]+'!');}else{window.Engine.removeRandomKeyword(G,targets[0]);}window.Engine.gainInsight(G,idx,2);} } };
CARD_DEFS['M104'] = { id:'M104', hero:'archmage', name:'Void Collapse', type:'curse', cost:4, starter:false, isToken:false, kw:{}, text:'Target enemy minion loses all keywords. Freeze it. Gain 3 Insight.', targetType:'enemy_minion', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.silenceMinion(G,targets[0]);window.Engine.freezeMinion(G,targets[0],1);window.Engine.gainInsight(G,idx,3);} } };
CARD_DEFS['M105'] = { id:'M105', hero:'archmage', name:'Reality Fracture', type:'curse', cost:6, starter:false, isToken:false, kw:{}, text:'Target enemy minion loses all keywords and gets -3/-0. Draw 2 cards.', targetType:'enemy_minion', battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:(G,uid,idx,targets)=>{ if(targets&&targets[0]){window.Engine.silenceMinion(G,targets[0]);window.Engine.buffMinion(G,targets[0],-3,0,true);window.Engine.drawCards(G,idx,2);} } };

// ============================================================
// TOKEN DEFINITIONS
// ============================================================
TOKEN_DEFS['TK_WOLF']          = { id:'TK_WOLF',          hero:'token', name:'Wolf',           type:'minion', cost:0, isToken:true, baseAtk:2, baseHp:2, kw:{},                             text:'',                              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_TREANT']        = { id:'TK_TREANT',        hero:'token', name:'Treant',         type:'minion', cost:0, isToken:true, baseAtk:2, baseHp:2, kw:{taunt:true},                    text:'Taunt.',                        battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_ELEMENTAL']     = { id:'TK_ELEMENTAL',     hero:'token', name:'Elemental',      type:'minion', cost:0, isToken:true, baseAtk:3, baseHp:3, kw:{trample:true},                  text:'Trample.',                      battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_RAT']           = { id:'TK_RAT',           hero:'token', name:'Rat',            type:'minion', cost:0, isToken:true, baseAtk:1, baseHp:1, kw:{},                             text:'',                              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_RATSWARM']      = { id:'TK_RATSWARM',      hero:'token', name:'Rat Swarm',      type:'minion', cost:0, isToken:true, baseAtk:2, baseHp:1, kw:{},                             text:'Last Breath: Deal 1 damage to a random enemy minion.', battlecry:null, lastBreath:(G,uid,idx)=>{ const e=window.Engine.getEnemyMinions(G,idx); if(e.length>0) window.Engine.dealDamage(G,window.Engine.rand(e).uid,1,null); }, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_GOBLIN']        = { id:'TK_GOBLIN',        hero:'token', name:'Goblin',         type:'minion', cost:0, isToken:true, baseAtk:1, baseHp:1, kw:{},                             text:'',                              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_GOBLIN_WARRIOR']= { id:'TK_GOBLIN_WARRIOR',hero:'token', name:'Goblin Warrior', type:'minion', cost:0, isToken:true, baseAtk:2, baseHp:2, kw:{},                             text:'',                              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_SPIDER']        = { id:'TK_SPIDER',        hero:'token', name:'Spider',         type:'minion', cost:0, isToken:true, baseAtk:1, baseHp:1, kw:{deathtouch:true},               text:'Deathtouch.',                   battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_SHADOW']        = { id:'TK_SHADOW',        hero:'token', name:'Shadow',         type:'minion', cost:0, isToken:true, baseAtk:2, baseHp:1, kw:{stealth:true},                  text:'Stealth.',                      battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_SHADE']         = { id:'TK_SHADE',         hero:'token', name:'Shade',          type:'minion', cost:0, isToken:true, baseAtk:1, baseHp:1, kw:{stealth:true},                  text:'Stealth.',                      battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_SKELETON']      = { id:'TK_SKELETON',      hero:'token', name:'Skeleton',       type:'minion', cost:0, isToken:true, baseAtk:1, baseHp:1, kw:{},                             text:'',                              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_PHANTOM']       = { id:'TK_PHANTOM',       hero:'token', name:'Phantom',        type:'minion', cost:0, isToken:true, baseAtk:4, baseHp:4, kw:{stealth:true,menace:true},      text:'Stealth. Menace.',              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
TOKEN_DEFS['TK_SHEEP']         = { id:'TK_SHEEP',         hero:'token', name:'Sheep',          type:'minion', cost:0, isToken:true, baseAtk:1, baseHp:1, kw:{},                             text:'',                              battlecry:null, lastBreath:null, inspire:null, rally:null, surge:null, onPlay:null };
